### ISSUE TITLE
Option to set hook that described locally in project

### ISSUE THREAD

**Issue by npdev453** [swimauger/tsc-hooks#26]
So, as I can see there is only one way that to create own hook, it's post it to library in this repo. 

But sometimes need to create hooks locally, for private project especially. 
For now, I found a dirty way, with passing `../../../path` to the `hooks` config.

```
  "hooks": [
    "../../../copy-files2"
  ]
```

But I think, that `thc-hooks` should check if hook name starts with './' it's  an local script, else it library script. (like `require` do)

**Comment by swimauger** [comment]
Yeah this is actually already supported, I have just been too lazy to add it to the docs 😆

Take a look here https://github.com/swimauger/tsc-hooks/blob/main/lib/utils/requireHook.js,

As you may be able to tell, `tsc-hooks` first attempts to see if the developer has entered a URL in hooks, if they have not, then it checks if the developer has specified a relative path, and then again if they have not, then it will use `tsc-hooks` already integrated hooks.

Currently, I have it setup, so that it reads the extension first to determine if it is not a hook from `tsc-hooks`, so you have to end the hook with .js if you want to use a local or externally hosted hook.

So to answer this, if you want a local hook specify:
```json5
  "hooks": [
    "./copy-files2.js" // Where copy-files2.js is in the same directory as your tsconfig.json 
  ]
```

If you want a hook from a url, specify:
```json5
  "hooks": [
    "https://somewebsite.com/myhooks/hook.js" // Just paste a url in with the .js extension (and uses the tsc-hooks framework)
  ]
```

In the future, I may change this so the .js extension is not needed, but for now there are some other priority items to finish.

**Comment by npdev453** [comment]
@swimauger 
Ah, sorry, I did not see that in this case I should also add extension ending. 

So, I think that error in this case could be more helpfully, now they throw only one path, but checks more.
```
npx tsc
Cannot find module '.\node_modules\tsc-hooks\hooks\scripts\ci\copy-files\scripts\ci\copy-files.hook'
```
Another thing, that if module know that I pass a relative path (started with ./) he could throw more concreted error with path that he really check. (or of arrays of paths)

And yes, looks like some documentations or examples can help much early.
